name: Python CI/CD

# Khi nào workflow này được kích hoạt
on:
  push:
    branches:
      - main    # Kích hoạt khi có push vào nhánh main
  pull_request:
    branches:
      - main    # Kích hoạt khi có pull request tới nhánh main

# Xác định các job sẽ chạy trong workflow
jobs:
  test:
    # Chạy trên môi trường Ubuntu
    runs-on: ubuntu-latest

    # Bước để thiết lập môi trường Python
    steps:
      # Check out code từ repository
      - name: Check out code
        uses: actions/checkout@v2

      # Thiết lập môi trường Python 3.9
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Cài đặt các dependencies từ requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Chạy pytest để kiểm tra mã nguồn
      - name: Run tests with pytest
        run: |
          pytest --maxfail=5 --disable-warnings