version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      PORT: 3000
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
